<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
	<LangVersion>13.0</LangVersion>
	<AllowUnsafeBlocks>True</AllowUnsafeBlocks>

	<!-- BO build script properties -->
	<ModFolder>WMITF</ModFolder>
	<ModInfoFolder>ModInfo</ModInfoFolder>
	<ModDLLFolder>patchers</ModDLLFolder>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="5.4.21" />
    <PackageReference Include="UnityEngine.Modules" Version="2020.3.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>compile</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="set &quot;outdir=$(OutDir)&quot;&#xD;&#xA;set &quot;assemblyname=$(AssemblyName)&quot;&#xD;&#xA;set &quot;modfolder=$(ModFolder)&quot;&#xD;&#xA;set &quot;modinfofolder=$(ModInfoFolder)&quot;&#xD;&#xA;set &quot;dllfolder=$(ModDLLFolder)&quot;&#xD;&#xA;call bobuild_win.bat" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
    <Exec Command="export OUTDIR=&quot;$(OutDir)&quot;&#xD;&#xA;export ASSEMBLYNAME=&quot;$(AssemblyName)&quot;&#xD;&#xA;export MODFOLDER=&quot;$(ModFolder)&quot;&#xD;&#xA;export MODINFOFOLDER=&quot;$(ModInfoFolder)&quot;&#xD;&#xA;export DLLFOLDER=&quot;$(ModDLLFolder)&quot;&#xD;&#xA;./bobuild_lin.sh" Condition="$([MSBuild]::IsOSPlatform('Linux'))" />
  </Target>

</Project>
